fitness_keywords = [
    'exercise', 'workout', 'diet', 'nutrition', 'calories', 
    'fitness', 'fit', 'strength', 'strong', 'training', 
    'weight', 'muscle', 'muscular', 'cardio', 'cardiovascular', 
    'aerobic', 'protein', 'health', 'healthy', 'lifestyle', 
    'gym', 'push-ups', 'push ups', 'plank', 'squat', 'lunges', 
    'deadlift', 'bench press', 'burpees', 'cycling', 
    'biking', 'bicycle', 'running', 'jogging', 'swimming', 
    'yoga', 'pilates', 'aerobics', 'zumba', 'crossfit', 
    'HIIT', 'high-intensity interval training', 'stretching', 
    'flexibility', 'recovery', 'wellness', 'hydration', 
    'hydrating', 'macros', 'macronutrients', 'micros', 
    'micronutrients', 'football', 'soccer', 'basketball', 
    'baseball', 'tennis', 'badminton', 'volleyball', 
    'netball', 'cricket', 'rugby', 'hockey', 'golf', 
    'boxing', 'martial arts', 'karate', 'taekwondo', 
    'judo', 'ballet', 'dance', 'rowing', 'canoeing', 
    'kayaking', 'rock climbing', 'climbing', 'hiking', 
    'trail running', 'triathlon', 'ironman', 'marathon', 
    'sprint', 'sprinting', 'skipping', 'jump rope', 
    'jumprope', 'sled push', 'mountain climbers', 'hench',
    'bodybuilding', 'bodybuilder', 'powerlifting', 
    'powerlifter', 'calisthenics', 'gymnastics', 'parkour', 
    'surfing', 'skateboarding', 'snowboarding', 'skiing', 
    'diving', 'snorkeling', 'fencing', 'archery', 'equestrian', 
    'horse riding', 'handball', 'softball', 'lacrosse', 
    'pickleball', 'paddleboarding', 'sailing', 'windsurfing', 
    'parasailing', 'motocross', 'BMX', 'strength training', 
    'conditioning', 'personal training', 'personal trainer', 
    'group fitness', 'meditation', 'mindfulness', 
    'breathing exercises', 'resistance training', 
    'strengthening', 'endurance', 'stamina', 'balance', 
    'coordination', 'agility', 'speed', 'power', 
    'athletic', 'athlete', 'bodyweight', 'circuit training', 
    'core', 'core strength', 'abdominal', 'abs', 
    'obliques', 'biceps', 'triceps', 'forearms', 
    'shoulders', 'deltoids', 'traps', 'trapezius', 
    'pectorals', 'chest', 'back', 'lats', 'latissimus dorsi', 
    'glutes', 'gluteus', 'quadriceps', 'quads', 
    'hamstrings', 'calves', 'gains', 'lean', 'bulk', 
    'cutting', 'bulking', 'shredded', 'toned', 'ripped', 
    'vascularity', 'metabolism', 'resting', 'rest days', 
    'active recovery', 'fitness routine', 'workout plan', 
    'fitness plan', 'meal plan', 'nutrition plan', 'muscly', 'muscles',
    'diet plan', 'supplements', 'multivitamins', 
    'pre-workout', 'post-workout', 'protein shake', 
    'protein powder', 'whey protein', 'casein protein', 
    'BCAAs', 'branched-chain amino acids', 'creatine', 
    'glutamine', 'hydration', 'electrolytes', 
    'sports drink', 'water', 'sleep', 'rest', 'recovery time', 
    'mental health', 'mental fitness', 'stress management', 
    'stress relief', 'cardio workout', 'strength workout', 
    'resistance workout', 'HIIT workout', 'low impact', 
    'high impact', 'moderate intensity', 'high intensity', 
    'fitness goals', 'weight loss', 'muscle gain', 
    'fat loss', 'body fat', 'body composition', 
    'BMI', 'body mass index', 'BMR', 'basal metabolic rate', 
    'TDEE', 'total daily energy expenditure', 'caloric intake', 
    'caloric deficit', 'caloric surplus', 'macronutrient ratio', 
    'meal prep', 'food prep', 'cooking', 'recipes', 
    'healthy eating', 'clean eating', 'balanced diet', 
    'portion control', 'nutrition facts', 'food labels', 
    'organic', 'natural', 'whole foods', 'processed foods', 
    'junk food', 'fast food', 'cheat meal', 'cheat day', 
    'vegetables', 'fruits', 'lean meats', 'poultry', 
    'fish', 'seafood', 'nuts', 'seeds', 'whole grains', 
    'legumes', 'dairy', 'yogurt', 'cheese', 'milk', 
    'plant-based', 'vegan', 'vegetarian', 'paleo', 
    'keto', 'ketogenic', 'low-carb', 'high-carb', 
    'low-fat', 'high-fat', 'low-protein', 'high-protein', 
    'fiber', 'fibrous', 'glycemic index', 'GI', 
    'blood sugar', 'insulin', 'hormones', 'thyroid', 
    'adrenal', 'cortisol', 'testosterone', 'estrogen', 
    'menopause', 'pregnancy', 'postpartum', 'child fitness', 
    'senior fitness', 'adaptive fitness', 'disability fitness', 
    'inclusive fitness', 'sports performance', 'athletic training', 
    'sports science', 'exercise science', 'kinesiology', 
    'biomechanics', 'physical therapy', 'physiotherapy', 
    'rehabilitation', 'injury prevention', 'injury recovery', 
    'sports injury', 'sprains', 'strains', 'fractures', 
    'dislocations', 'bruises', 'contusions', 'swelling', 
    'inflammation', 'pain management', 'massage', 
    'sports massage', 'deep tissue massage', 'foam rolling', 
    'myofascial release', 'stretch therapy', 'chiropractic', 
    'acupuncture', 'dry needling', 'cupping', 'taping', 
    'kinesio tape', 'sports taping', 'compression', 
    'compression garments', 'knee sleeves', 'elbow sleeves', 
    'wrist wraps', 'lifting belts', 'weightlifting shoes', 
    'running shoes', 'cross-training shoes', 'fitness apparel', 
    'athleisure', 'sportswear', 'activewear', 'fitness tracker', 
    'smartwatch', 'heart rate monitor', 'GPS watch', 
    'pedometer', 'step counter', 'activity tracker', 
    'fitness app', 'fitness technology', 'wearable tech', 
    'online coaching', 'virtual training', 'fitness community', 
    'support group', 'accountability', 'motivation', 
    'inspiration', 'fitness influencer', 'personal best', 
    'PR', 'personal record', 'one rep max', '1RM', 
    'progression', 'progressive overload', 'periodization', 
    'training cycle', 'training program', 'workout schedule', 
    'split routine', 'full-body workout', 'upper body', 
    'lower body', 'core workout', 'ab workout', 'leg day', 
    'arm day', 'chest day', 'back day', 'shoulder day', 
    'reps', 'repetitions', 'sets', 'circuit', 'superset', 
    'drop set', 'giant set', 'compound exercise', 
    'isolation exercise', 'functional training', 'dynamic warm-up', 
    'cool down', 'foam roller', 'resistance band', 'kettlebell', 
    'dumbbell', 'barbell', 'weight plate', 'weight rack', 
    'pull-up bar', 'dip station', 'bench', 'squat rack', 
    'power rack', 'smith machine', 'cable machine', 
    'lat pulldown', 'leg press', 'leg curl', 'leg extension', 
    'chest press', 'shoulder press', 'row machine', 
    'rowing machine', 'treadmill', 'elliptical', 
    'stationary bike', 'spin bike', 'exercise bike', 
    'stair climber', 'step machine', 'stepper', 
    'battle ropes', 'medicine ball', 'slam ball', 
    'stability ball', 'Bosu ball', 'balance board', 'arms', 'bum', 'glutes', 'legs', 'pecs', 'chest', 'calves'
    ]

greeting_words = [
    'hello', 'hi', 'howdy', 'hey', 'greetings', 'salutations',
    'welcome', 'what’s up', 'yo', 'hiya', 'good day', 'morning',
    'whats up',
    'afternoon', 'evening', 'good to see you', 'how are you', 
    'how’s it going', 'what’s going on', 'what’s new', 'howdy-do',
    'hows it going', 'whats going on', 'whats new'
    'how do you do', 'hey there', 'hello there', 'hi there', 
    'hey hey', 'sup', 'what’s happening', 'nice to meet you', 
    'pleased to meet you', 'long time no see', 'hi everyone', 
    'how have you been', 'how are you doing', 'hey buddy', 
    'how’s everything', 'how’s life', 'how’s things', 'hiya', 
    'hows everything', 'hows life', 'hows things',
    'good morning', 'good afternoon', 'good evening', 
    'top of the morning to you', 'yo yo', 'hey ya', 'aloha', 
    'bonjour', 'hola', 'salut', 'ciao', 'namaste', 'shalom', 
    'hi there'
]

continuation_terms = [
    'continue', 'more', 'carry on', 'go on', 'proceed', 
    'further', 'keep going', 'keep on', 'go ahead', 'extend', 
    'elaborate', 'expand', 'add on', 'go into detail', 
    'tell me more', 'give me more', 'keep telling me', 'keep it up', 
    'go further', 'give details', 'provide more info', 'keep explaining', 
    'keep describing', 'keep talking', 'give more information', 
    'say more', 'more details', 'details please', 'go deeper', 
    'can you elaborate', 'can you explain more', 'can you expand on that', 
    'keep elaborating', 'additional information', 'add details', 
    'add more', 'continue explaining', 'continue describing', 
    'please continue', 'please go on', 'continue please', 
    'expand please', 'elaborate please', 'more info', 
    'give me additional details', 'add information', 'tell me further', 'give me specifics', 'break it down'
]

prompt_allowed = fitness_keywords + greeting_words + continuation_terms

satisfied_terms = [
    'thanks', 'thank you', 'great', 'ok', 'okay', 'got it', 'good',
    'understood', 'cool', 'awesome', 'perfect', 'sounds good', 
    'that’s it', 'that’s all',  
    'thats it', 'thats all', 'clear', 'fine',
    'all set', 'good', 'excellent', 'super', 'fantastic', 
    'wonderful', 'brilliant', 'terrific', 'amazing', 
    'fine', 'alright', 'fine with me', 'this is good', 'this works', 
    'works for me', 'I’m happy', 'I’m satisfied', 'satisfied', 
    'Im happy', 'Im satisfied',
    'no problem', 'A-OK', 'roger that', 'affirmative', 'splendid', 
    'very good', 'much appreciated', 'I appreciate it', 'grateful', 
    'many thanks', 'I’m good', 'no issues', 'no doubts', 
    'all clear', 'this helps', 'this is helpful', 'it’s clear', 
    'I’m clear', 'everything is clear', 'it’s fine', 'no worries', 
    'no concerns', 'clear enough', 'that’s clear', 'you’ve been helpful', 
    'you’ve been great', 'you’ve been fantastic', 'this is perfect', 
    'this is excellent', 'you rock', 'you’re the best', 'I’m okay', 
    'I’m okay with this', 'this is what I needed', 'this is exactly what I needed'
]

closing_terms = [
    'no', 'nah', 'nope', 'I’m done', 'Im done', 'goodbye', 
    'I want to go', 'no further questions', 'no more questions', 
    'bye', 'see you', 'see ya', 'later', 'catch you later', 
    'I’m out', 'Im out', 'that’s all', 'that’s it', 
    'all done', 'all set', 'finished', 'I’m finished', 
    'I’m leaving', 
    'Im leaving', 'I have to go', 'I gotta go', 'I need to go', 
    'I must go', 'time to go', 'exit', 'quit', 'end', 
    'terminate', 'log off', 'sign off', 'disconnect', 
    'close', 'shut down', 'finish', 
    'I’m signing off', 'Im signing off', 'I’m logging off', 
    'Im logging off', 'I’m quitting', 'Im quitting', 
    'I’m exiting', 'Im exiting', 'that will be all'
]

