fitness_keywords = [
    'exercise', 'workout', 'diet', 'nutrition', 'calories', 
    'fitness', 'fit', 'strength', 'strong', 'training', 
    'weight', 'muscle', 'muscular', 'cardio', 'cardiovascular', 
    'aerobic', 'protein', 'health', 'healthy', 'lifestyle', 
    'gym', 'push-ups', 'push ups', 'plank', 'squat', 'lunges', 
    'deadlift', 'bench press', 'burpees', 'cycling', 
    'biking', 'bicycle', 'running', 'jogging', 'swimming', 
    'yoga', 'pilates', 'aerobics', 'zumba', 'crossfit', 
    'HIIT', 'high-intensity interval training', 'stretching', 
    'flexibility', 'recovery', 'wellness', 'hydration', 
    'hydrating', 'macros', 'macronutrients', 'micros', 
    'micronutrients', 'football', 'soccer', 'basketball', 
    'baseball', 'tennis', 'badminton', 'volleyball', 
    'netball', 'cricket', 'rugby', 'hockey', 'golf', 
    'boxing', 'martial arts', 'karate', 'taekwondo', 
    'judo', 'ballet', 'dance', 'rowing', 'canoeing', 
    'kayaking', 'rock climbing', 'climbing', 'hiking', 
    'trail running', 'triathlon', 'ironman', 'marathon', 
    'sprint', 'sprinting', 'skipping', 'jump rope', 
    'jumprope', 'sled push', 'mountain climbers', 
    'bodybuilding', 'bodybuilder', 'powerlifting', 
    'powerlifter', 'calisthenics', 'gymnastics', 'parkour', 
    'surfing', 'skateboarding', 'snowboarding', 'skiing', 
    'diving', 'snorkeling', 'fencing', 'archery', 'equestrian', 
    'horse riding', 'handball', 'softball', 'lacrosse', 
    'pickleball', 'paddleboarding', 'sailing', 'windsurfing', 
    'parasailing', 'motocross', 'BMX', 'strength training', 
    'conditioning', 'personal training', 'personal trainer', 
    'group fitness', 'meditation', 'mindfulness', 
    'breathing exercises', 'resistance training', 
    'strengthening', 'endurance', 'stamina', 'balance', 
    'coordination', 'agility', 'speed', 'power', 
    'athletic', 'athlete', 'bodyweight', 'circuit training', 
    'core', 'core strength', 'abdominal', 'abs', 
    'obliques', 'biceps', 'triceps', 'forearms', 
    'shoulders', 'deltoids', 'traps', 'trapezius', 
    'pectorals', 'chest', 'back', 'lats', 'latissimus dorsi', 
    'glutes', 'gluteus', 'quadriceps', 'quads', 
    'hamstrings', 'calves', 'gains', 'lean', 'bulk', 
    'cutting', 'bulking', 'shredded', 'toned', 'ripped', 
    'vascularity', 'metabolism', 'resting', 'rest days', 
    'active recovery', 'fitness routine', 'workout plan', 
    'fitness plan', 'meal plan', 'nutrition plan', 
    'diet plan', 'supplements', 'multivitamins', 
    'pre-workout', 'post-workout', 'protein shake', 
    'protein powder', 'whey protein', 'casein protein', 
    'BCAAs', 'branched-chain amino acids', 'creatine', 
    'glutamine', 'hydration', 'electrolytes', 
    'sports drink', 'water', 'sleep', 'rest', 'recovery time', 
    'mental health', 'mental fitness', 'stress management', 
    'stress relief', 'cardio workout', 'strength workout', 
    'resistance workout', 'HIIT workout', 'low impact', 
    'high impact', 'moderate intensity', 'high intensity', 
    'fitness goals', 'weight loss', 'muscle gain', 
    'fat loss', 'body fat', 'body composition', 
    'BMI', 'body mass index', 'BMR', 'basal metabolic rate', 
    'TDEE', 'total daily energy expenditure', 'caloric intake', 
    'caloric deficit', 'caloric surplus', 'macronutrient ratio', 
    'meal prep', 'food prep', 'cooking', 'recipes', 
    'healthy eating', 'clean eating', 'balanced diet', 
    'portion control', 'nutrition facts', 'food labels', 
    'organic', 'natural', 'whole foods', 'processed foods', 
    'junk food', 'fast food', 'cheat meal', 'cheat day', 
    'vegetables', 'fruits', 'lean meats', 'poultry', 
    'fish', 'seafood', 'nuts', 'seeds', 'whole grains', 
    'legumes', 'dairy', 'yogurt', 'cheese', 'milk', 
    'plant-based', 'vegan', 'vegetarian', 'paleo', 
    'keto', 'ketogenic', 'low-carb', 'high-carb', 
    'low-fat', 'high-fat', 'low-protein', 'high-protein', 
    'fiber', 'fibrous', 'glycemic index', 'GI', 
    'blood sugar', 'insulin', 'hormones', 'thyroid', 
    'adrenal', 'cortisol', 'testosterone', 'estrogen', 
    'menopause', 'pregnancy', 'postpartum', 'child fitness', 
    'senior fitness', 'adaptive fitness', 'disability fitness', 
    'inclusive fitness', 'sports performance', 'athletic training', 
    'sports science', 'exercise science', 'kinesiology', 
    'biomechanics', 'physical therapy', 'physiotherapy', 
    'rehabilitation', 'injury prevention', 'injury recovery', 
    'sports injury', 'sprains', 'strains', 'fractures', 
    'dislocations', 'bruises', 'contusions', 'swelling', 
    'inflammation', 'pain management', 'massage', 
    'sports massage', 'deep tissue massage', 'foam rolling', 
    'myofascial release', 'stretch therapy', 'chiropractic', 
    'acupuncture', 'dry needling', 'cupping', 'taping', 
    'kinesio tape', 'sports taping', 'compression', 
    'compression garments', 'knee sleeves', 'elbow sleeves', 
    'wrist wraps', 'lifting belts', 'weightlifting shoes', 
    'running shoes', 'cross-training shoes', 'fitness apparel', 
    'athleisure', 'sportswear', 'activewear', 'fitness tracker', 
    'smartwatch', 'heart rate monitor', 'GPS watch', 
    'pedometer', 'step counter', 'activity tracker', 
    'fitness app', 'fitness technology', 'wearable tech', 
    'online coaching', 'virtual training', 'fitness community', 
    'support group', 'accountability', 'motivation', 
    'inspiration', 'fitness influencer', 'personal best', 
    'PR', 'personal record', 'one rep max', '1RM', 
    'progression', 'progressive overload', 'periodization', 
    'training cycle', 'training program', 'workout schedule', 
    'split routine', 'full-body workout', 'upper body', 
    'lower body', 'core workout', 'ab workout', 'leg day', 
    'arm day', 'chest day', 'back day', 'shoulder day', 
    'reps', 'repetitions', 'sets', 'circuit', 'superset', 
    'drop set', 'giant set', 'compound exercise', 
    'isolation exercise', 'functional training', 'dynamic warm-up', 
    'cool down', 'foam roller', 'resistance band', 'kettlebell', 
    'dumbbell', 'barbell', 'weight plate', 'weight rack', 
    'pull-up bar', 'dip station', 'bench', 'squat rack', 
    'power rack', 'smith machine', 'cable machine', 
    'lat pulldown', 'leg press', 'leg curl', 'leg extension', 
    'chest press', 'shoulder press', 'row machine', 
    'rowing machine', 'treadmill', 'elliptical', 
    'stationary bike', 'spin bike', 'exercise bike', 
    'stair climber', 'step machine', 'stepper', 
    'battle ropes', 'medicine ball', 'slam ball', 
    'stability ball', 'Bosu ball', 'balance board'
    ]

greeting_words = [
    'hello', 'hi', 'howdy', 'hey', 'greetings', 'salutations', 
    'welcome', 'what’s up', 'yo', 'hiya', 'good day', 'morning', 
    'afternoon', 'evening', 'good to see you'
]

continuation_terms = [
    'continue', 'more', 'carry on', 'go on', 'proceed', 
    'further', 'keep going', 'keep on', 'go ahead', 'extend', 
    'elaborate', 'expand', 'add on', 'go into detail'
]

prompt_allowed = fitness_keywords + greeting_words + continuation_terms
